#!/bin/sh
### BEGIN INIT INFO
# Provides:          rpa-colmeia
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Descrição curta do serviço
# Description:       Descrição detalhada do serviço
### END INIT INFO

# Comandos para iniciar o serviço
case "$1" in
    start)
        node /app/service/index.js
        ;;
    *)
        echo "Uso: /etc/init.d/rpa-colmeia {start}"
        exit 1
        ;;
esac

exit 0